apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: visionaid-gitlab-runner
spec:
  interval: 5m
  chart:
    spec:
      chart: 'gitlab-runner'
      version: '0.52.x'
      sourceRef:
        kind: HelmRepository
        name: gitlab-repository
      interval: 1m
  values:
    replicaCount: 1
  valuesFrom:
    - kind: ConfigMap
      name: gitlab-runner-config