apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-release.yaml
configMapGenerator:
- name: gitlab-runner-config
  files:
    - values.yaml
configurations:
  - kustomize-config.yaml