---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: bus-screen-text-detector
  namespace: visionaid-flux-system
spec:
  interval: 1m0s
  path: ./bus-screen-text-detector/
  prune: true
  sourceRef:
    kind: GitRepository
    name: visionaid-manifests
  targetNamespace: visionaid-flux-system

