---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: bus-screen-text-detector-prod
  namespace: visionaid-flux-system
spec:
  filterTags:
    extract: $ts
    pattern: '^main-(?P<ts>[0-9]*)'
  imageRepositoryRef:
    name: bus-screen-text-detector
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: bus-screen-text-detector-dev
  namespace: visionaid-flux-system
spec:
  filterTags:
    extract: $ts
    pattern: '^dev-(?P<ts>[0-9]*)'
  imageRepositoryRef:
    name: bus-screen-text-detector
  policy:
    alphabetical:
      order: asc