---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: bus-screen-cropper
  namespace: visionaid-flux-system
spec:
  image: registry.forge.hefr.ch/pi_aimarket-visionaid/bus-screen-cropper/visionaid-bus-screen-cropper
  interval: 1m0s
  secretRef:
    name: visionaid-regsecret

