apiVersion: v1
kind: Service
metadata:
  name: visionaid-object-to-nlp
  namespace: visionaid-flux-system
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: visionaid-object-to-nlp
  ports:
  - protocol: TCP
    port: 8000