apiVersion: apps/v1
kind: Deployment
metadata:
  name: visionaid-bus-screen-text-detector
  namespace: visionaid-flux-system
  labels:
    app: visionaid-bus-screen-text-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visionaid-bus-screen-text-detector
  template:
    metadata:
      labels:
        app: visionaid-bus-screen-text-detector
    spec:
      containers:
      - name: visionaid-bus-screen-text-detector
        image: registry.forge.hefr.ch/pi_aimarket-visionaid/bus-screen-text-detector/visionaid-bus-screen-text-detector:1683278969 # {"$imagepolicy": "visionaid-flux-system:bus-screen-text-detector"}
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: visionaid-regsecret
