apiVersion: v1
kind: Service
metadata:
  name: object-detector
  namespace: pi_aimarket-visionaid
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: object-detector
  ports:
  - protocol: TCP
    port: 8000