---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: photo-validator
  namespace: visionaid-flux-system
spec:
  interval: 1m0s
  path: ./photo-validator/
  prune: true
  sourceRef:
    kind: GitRepository
    name: visionaid-manifests
  targetNamespace: visionaid-flux-system

