---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: photo-validator-prod
  namespace: visionaid-flux-system
spec:
  filterTags:
    extract: $ts
    pattern: '^main-(?P<ts>[0-9]*)'
  imageRepositoryRef:
    name: photo-validator
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: photo-validator-dev
  namespace: visionaid-flux-system
spec:
  filterTags:
    extract: $ts
    pattern: '^dev-(?P<ts>[0-9]*)'
  imageRepositoryRef:
    name: photo-validator
  policy:
    alphabetical:
      order: asc

