apiVersion: apps/v1
kind: Deployment
metadata:
  name: visionaid-object-detector-deployment
  namespace: visionaid-flux-system
  labels:
    app: visionaid-object-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visionaid-object-detector
  template:
    metadata:
      labels:
        app: visionaid-object-detector
    spec:
      containers:
      - name: visionaid-object-detector
        image: registry.forge.hefr.ch/pi_aimarket-visionaid/object-detector/visionaid-object-detector:1683736320 # {"$imagepolicy": "visionaid-flux-system:object-detector"}
        ports:
        - containerPort: 8000
        resources:
          requests:
            tencent.com/vcuda-core: 20
            tencent.com/vcuda-memory: 16
          limits:
            tencent.com/vcuda-core: 20
            tencent.com/vcuda-memory: 16
      imagePullSecrets:
      - name: visionaid-regsecret
