apiVersion: v1
kind: Service
metadata:
  name: visionaid-zero-shot-object-detector
  namespace: visionaid-flux-system
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: visionaid-zero-shot-object-detector
  ports:
  - protocol: TCP
    port: 8000