---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: object-to-nlp
  namespace: visionaid-flux-system
spec:
  image: registry.forge.hefr.ch/pi_aimarket-visionaid/object-to-nlp/visionaid-object-to-nlp
  interval: 1m0s
  secretRef:
    name: visionaid-regsecret

