apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - persistentvolumeclaim.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
- name: grafana-server-conf
  files:
    - datasource.yaml
