---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: photo-validator
  namespace: visionaid-flux-system
spec:
  image: registry.forge.hefr.ch/pi_aimarket-visionaid/photo-validator/visionaid-photo-validator
  interval: 1m0s
  secretRef:
    name: visionaid-regsecret

