apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
nameSuffix: '-dev'
images:
  - name: registry.forge.hefr.ch/pi_aimarket-visionaid/bus-screen-text-detector/visionaid-bus-screen-text-detector
    newTag: "dev-1686182155" # {"$imagepolicy": "visionaid-flux-system:bus-screen-text-detector-dev:tag"}
transformers:
  - |-
    apiVersion: builtin
    kind: LabelTransformer
    metadata:
      name: commonLabelsTransformer
    labels:
      environment: dev
    fieldSpecs:
    - path: spec/template/metadata/labels
      create: true
      kind: Deployment
    - path: spec/selector/matchLabels
      create: true
      kind: Deployment
    - path: spec/selector
      kind: Service
      create: true
