---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: zero-shot-object-detector
  namespace: visionaid-flux-system
spec:
  image: registry.forge.hefr.ch/pi_aimarket-visionaid/zero-shot-object-detector/visionaid-zero-shot-object-detector
  interval: 1m0s
  secretRef:
    name: visionaid-regsecret

