apiVersion: apps/v1
kind: Deployment
metadata:
  name: visionaid-object-to-nlp-deployment
  namespace: visionaid-flux-system
  labels:
    app: visionaid-object-to-nlp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visionaid-object-to-nlp
  template:
    metadata:
      labels:
        app: visionaid-object-to-nlp
    spec:
      containers:
      - name: visionaid-object-to-nlp
        image: registry.forge.hefr.ch/pi_aimarket-visionaid/object-to-nlp/visionaid-object-to-nlp:1683736353 # {"$imagepolicy": "visionaid-flux-system:object-to-nlp"}
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: visionaid-object-to-nlp-secret
              key: OPENAI_API_KEY
      imagePullSecrets:
      - name: visionaid-regsecret
