apiVersion: apps/v1
kind: Deployment
metadata:
  name: visionaid-bus-screen-cropper
  namespace: visionaid-flux-system
  labels:
    app: visionaid-bus-screen-cropper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visionaid-bus-screen-cropper
  template:
    metadata:
      labels:
        app: visionaid-bus-screen-cropper
    spec:
      containers:
      - name: visionaid-bus-screen-cropper
        image: registry.forge.hefr.ch/pi_aimarket-visionaid/bus-screen-cropper/visionaid-bus-screen-cropper:1683736201 # {"$imagepolicy": "visionaid-flux-system:bus-screen-cropper"}
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: visionaid-regsecret
