apiVersion: v1
kind: Service
metadata:
  name: visionaid-bus-screen-cropper
  namespace: visionaid-flux-system
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: visionaid-bus-screen-cropper
  ports:
  - protocol: TCP
    port: 8000