version: '3'
services:
  cml-runner:
    build: .
    environment:
      #GITLAB_TOKEN: ${GITLAB_TOKEN}
      IN_DOCKER: ''
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    ipc: host
