apiVersion: apps/v1
kind: Deployment
metadata:
  name: visionaid-gateway-mongodb-deployment
  namespace: visionaid-flux-system
  labels:
    app: visionaid-gateway-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visionaid-gateway-mongodb
  template:
    metadata:
      labels:
        app: visionaid-gateway-mongodb
    spec:
      containers:
      - name: visionaid-gateway-mongodb
        image: mongo:5.0.17
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: /data/db
            name: visionaid-gateway-mongodb-pvc
      volumes:
      - name: visionaid-gateway-mongodb-pvc
        persistentVolumeClaim:
          claimName: visionaid-gateway-mongodb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: visionaid-gateway-mongodb-pvc
  namespace: visionaid-flux-system
  labels:
    app: visionaid-gateway-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
