apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
nameSuffix: '-prod'
images:
  - name: registry.forge.hefr.ch/pi_aimarket-visionaid/object-to-nlp/visionaid-object-to-nlp
    newTag: "main-1685901765" # {"$imagepolicy": "visionaid-flux-system:object-to-nlp-prod:tag"}
transformers:
  - |-
    apiVersion: builtin
    kind: LabelTransformer
    metadata:
      name: commonLabelsTransformer
    labels:
      environment: prod
    fieldSpecs:
    - path: spec/template/metadata/labels
      create: true
      kind: Deployment
    - path: spec/selector/matchLabels
      create: true
      kind: Deployment
    - path: spec/selector
      kind: Service
      create: true
