---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: frontend
  namespace: visionaid-flux-system
spec:
  image: registry.forge.hefr.ch/pi_aimarket-visionaid/frontend/visionaid-frontend
  interval: 1m0s
  secretRef:
    name: visionaid-regsecret

