apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
nameSuffix: '-dev'
images:
  - name: registry.forge.hefr.ch/pi_aimarket-visionaid/frontend/visionaid-frontend
    newTag: "dev-1685890422" # {"$imagepolicy": "visionaid-flux-system:frontend-dev:tag"}
patches:
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: visionaid-dev.kube.isc.heia-fr.ch
      - op: replace
        path: /spec/tls/0/hosts/0
        value: visionaid-dev.kube.isc.heia-fr.ch
transformers:
  - |-
    apiVersion: builtin
    kind: LabelTransformer
    metadata:
      name: commonLabelsTransformer
    labels:
      environment: dev
    fieldSpecs:
    - path: spec/template/metadata/labels
      create: true
      kind: Deployment
    - path: spec/selector/matchLabels
      create: true
      kind: Deployment
    - path: spec/selector
      kind: Service
      create: true
