---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: visionaid-manifests
  namespace: visionaid-flux-system
spec:
  interval: 1m0s
  secretRef:
    name: visionaid-manifests-secret
  ref:
    branch: main
  url: https://gitlab.forge.hefr.ch/pi_aimarket-visionaid/ms-manifests

