apiVersion: v1
kind: Service
metadata:
  name: visionaid-label-studio-text-detector
  namespace: visionaid-flux-system
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: visionaid-label-studio-text-detector
  ports:
  - protocol: TCP
    port: 9000